# Generated by Django 4.2.3 on 2023-08-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_predev_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('Name', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=30)),
            ],
        ),
    ]
